// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoDCN0U6OHqnlEYaapx8tj_fbyiks-H1w',
    appId: '1:198146297205:web:6f376f484de07bbed5973c',
    messagingSenderId: '198146297205',
    projectId: 'flutterfire-ui-codelab-deda7',
    authDomain: 'flutterfire-ui-codelab-deda7.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-deda7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC82FLFfxIssSNc3XflvEC5QQGEQ8AUv0I',
    appId: '1:198146297205:android:3e7de7854e8bca33d5973c',
    messagingSenderId: '198146297205',
    projectId: 'flutterfire-ui-codelab-deda7',
    storageBucket: 'flutterfire-ui-codelab-deda7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZoLRYLnRV8FfMje_I6tTbBxCivTCSfBQ',
    appId: '1:198146297205:ios:e5ca035ecb94ba54d5973c',
    messagingSenderId: '198146297205',
    projectId: 'flutterfire-ui-codelab-deda7',
    storageBucket: 'flutterfire-ui-codelab-deda7.appspot.com',
    iosClientId: '198146297205-b5ebbbo4i6n7idab41184n383mvl7nkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZoLRYLnRV8FfMje_I6tTbBxCivTCSfBQ',
    appId: '1:198146297205:ios:e5ca035ecb94ba54d5973c',
    messagingSenderId: '198146297205',
    projectId: 'flutterfire-ui-codelab-deda7',
    storageBucket: 'flutterfire-ui-codelab-deda7.appspot.com',
    iosClientId: '198146297205-b5ebbbo4i6n7idab41184n383mvl7nkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );
}
